# -*- coding: utf-8 -*-
"""Listed0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19UgTJvx5nl_msxqXJctJyUmZlS_gqOLp
"""
a="aba23"
b=a.index('23')

import requests
from bs4 import BeautifulSoup

# url ="https://in.search.yahoo.com/search;_ylt=AwrKAmNgqz1k2DIAa1y7HAx.;_ylu=Y29sbwNzZzMEcG9zAzEEdnRpZAMEc2VjA3BhZ2luYXRpb24-?p=site%3Ayoutube.com+openinapp.co&pz=7&vm=r&type=E211IN885G91710&fr=mcafee&fr2=sb-top&b=0&pz=7&xargs=0"

# news = url[0:url.index("&b")+3]+str(14)+url[url.index("&b")+3+len(str(14)):]
# news

# response = requests.get(
#     url
# )

# beauty_code = BeautifulSoup(response.content, "html.parser")

# anchor_list = beauty_code.find_all("a")
# # anchor_list

# url ="https://www.google.com/search?q=site:youtube.com+openinapp.co&sxsrf=APwXEddRpXap1GiJ_yj18Q7n9st6_7mJQQ:1681764613380&ei=BbE9ZKnnFp6k2roPhf2y6Aw&start=10&sa=N&ved=2ahUKEwjp_YCz5bH-AhUeklYBHYW-DM0Q8tMDegQIEhAE&biw=1536&bih=792&dpr=1.25"

url ="https://www.bing.com/search?q=site:youtube.com+openinapp.co&PC=U316&first=0&FORM=PERE1"
url ="https://www.google.com/search?q=site%3Ayoutube.com%2Fuser+Nike"
url ="https://www.bing.com/search?q=site%3Ayoutube.com%2Fuser+Nike"
response = requests.get(url)
beauty_code = BeautifulSoup(response.content, "html.parser")
anchor_list = beauty_code.find_all("a")
anchor_list

# ‌FORM=PERE1‌：搜索结果以卡片形式展示，适用于图片或视频等多媒体类搜索场景‌
# PC=U316‌：表示搜索是在个人电脑上进行的‌

from selenium import webdriver
import json
from selenium.webdriver.support.select import Select

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("--headless")
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # 设置为无头模式
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('--disable-gpu')  # 禁用GPU加速
options.add_argument('--headless')

# 初始化 WebDriver
driver = webdriver.Chrome(options=options)
 
# 打开网页

import time
aaa=time.time()
url="https://www.google.com/search?q=site%3Ayoutube.com%2Fuser+Nike"
driver.get(url)
a=[i.get_attribute('href') for i in driver.find_elements(By.XPATH,'//*[@jsname="UWckNb"]')]
print(a)
# a=[i.text for i in driver.find_elements(By.XPATH,'//div[@class="yuRUbf"]')]
# print(a)
print(time.time()-aaa)
driver.quit()